import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Statically typed links: `href` on next/link and the next/navigation
  // methods are checked against the routes that actually exist, so a renamed
  // page can't leave a dead link behind. Types are (re)generated by
  // `next dev`, `next build`, or `next typegen`.
  typedRoutes: true,
};

export default nextConfig;
