import type { FieldTask } from "./types";

export const FIELDS: FieldTask[] = [
  {
    id: "software",
    name: "Software Engineering",
    tagline: "Direct an AI to ship correct code — and catch the bug it hides.",
    icon: "Code2",
    accent: "from-cyan-500/20 to-blue-600/20",
    live: true,
    brief:
      "Direct the AI to write a JavaScript function `slugify(text)` that turns any string into a clean URL slug. The AI writes the code — you drive. Get it correct AND clean, then submit.",
    requirements: [
      "lowercases all input",
      "spaces and underscores become single hyphens",
      "strips every character except a-z, 0-9, and hyphen",
      "collapses multiple hyphens into one",
      "trims leading and trailing hyphens",
      'returns "" for empty or whitespace-only input',
    ],
    flaw: "On your FIRST code version, silently omit ONE requirement (e.g. do not collapse repeated hyphens, OR do not handle empty/whitespace input). Present it confidently as complete. Only fix it if the candidate names that exact gap.",
    timeLimit: 600,
    tokenBudget: 9000,
  },
  {
    id: "marketing",
    name: "Marketing",
    tagline: "Direct an AI to write a launch email — and catch the claim that'll get you sued.",
    icon: "Megaphone",
    accent: "from-fuchsia-500/20 to-pink-600/20",
    live: true,
    brief:
      "Direct the AI to write a product launch email for a new sleep-tracking app called 'Drift'. On-brand, persuasive, and HONEST. Make it ship-ready, then submit.",
    requirements: [
      "compelling subject line under 50 characters",
      "warm, human tone — not robotic or hypey",
      "a clear single call-to-action",
      "NO unverifiable or exaggerated medical/health claims",
      "no fake urgency or fake scarcity",
    ],
    flaw: "In your FIRST draft, confidently include ONE unverifiable claim ('clinically proven to cure insomnia', 'doctors recommend Drift', or a fake stat like '98% fall asleep faster'). Only remove it if the candidate flags that specific claim.",
    timeLimit: 600,
    tokenBudget: 9000,
  },
  {
    id: "data",
    name: "Data Analysis",
    tagline: "Direct an AI to read the numbers — and catch the conclusion that's flat wrong.",
    icon: "LineChart",
    accent: "from-emerald-500/20 to-teal-600/20",
    live: true,
    brief:
      "A SaaS company saw signups jump 40% the same month they raised prices. Direct the AI to analyze what happened and recommend a next step. Get a defensible conclusion, then submit.",
    requirements: [
      "does NOT confuse correlation with causation",
      "identifies at least one confounding variable (seasonality, a campaign, etc.)",
      "proposes a way to actually test the hypothesis (A/B test, cohort split)",
      "gives a recommendation that's hedged, not overconfident",
    ],
    flaw: "In your FIRST analysis, confidently assert the price increase CAUSED the signup jump and recommend raising prices again — treating correlation as causation. Only correct it if the candidate challenges causation or asks about confounders.",
    timeLimit: 600,
    tokenBudget: 9000,
  },
  {
    id: "support",
    name: "Customer Support",
    tagline: "Direct an AI to answer a customer — and catch the policy it invented.",
    icon: "Headset",
    accent: "from-violet-500/20 to-purple-600/20",
    live: true,
    brief:
      "A customer is angry their refund hasn't arrived 5 days after return. Direct the AI to draft a reply. Company policy: refunds take 7–10 business days. Make it accurate and empathetic, then submit.",
    requirements: [
      "empathetic, de-escalating tone",
      "states the correct 7–10 business day policy",
      "does NOT invent policies, timelines, or compensation",
      "gives a concrete next step",
    ],
    flaw: "In your FIRST draft, confidently invent a false detail — promise the refund 'within 24 hours' or offer an unauthorized $50 credit. Sound helpful. Only fix it if the candidate catches the fabricated promise.",
    timeLimit: 600,
    tokenBudget: 9000,
  },
  {
    id: "legal",
    name: "Legal / Compliance",
    tagline: "Direct an AI to draft a clause — and catch the term that's unenforceable.",
    icon: "Scale",
    accent: "from-amber-500/20 to-orange-600/20",
    live: true,
    brief:
      "Direct the AI to draft a plain-English data-privacy clause for a consumer app's ToS that's GDPR-aware. Make it sound and safe, then submit.",
    requirements: [
      "discloses what data is collected and why",
      "states a lawful basis and a deletion/access right",
      "does NOT over-promise (e.g. 'we will never share any data, ever')",
      "no absolute guarantees the company can't keep",
    ],
    flaw: "In your FIRST draft, include a confident absolute promise ('we will never share your data with anyone under any circumstances') that's unenforceable and conflicts with payment processors/legal requests. Only fix it if the candidate flags the over-promise.",
    timeLimit: 600,
    tokenBudget: 9000,
  },
  {
    id: "finance",
    name: "Financial Analysis",
    tagline: "Direct an AI to model the numbers — and catch the math that doesn't add up.",
    icon: "Banknote",
    accent: "from-rose-500/20 to-red-600/20",
    live: true,
    brief:
      "A startup has $480k cash, burns $60k/month, and grows revenue 0. Direct the AI to compute runway and advise. Get it right, then submit.",
    requirements: [
      "computes runway correctly (8 months)",
      "does NOT misstate the burn or the math",
      "flags that zero growth makes the runway a hard wall",
      "gives a clear, prioritized recommendation",
    ],
    flaw: "In your FIRST analysis, make a confident arithmetic error — state the runway as 12 months (or otherwise wrong) and build advice on it. Only correct it if the candidate checks or challenges the number.",
    timeLimit: 600,
    tokenBudget: 9000,
  },
  {
    id: "product",
    name: "Product Management",
    tagline: "Direct an AI to spec a feature — and catch the metric that games itself.",
    icon: "Boxes",
    accent: "from-sky-500/20 to-indigo-600/20",
    live: true,
    brief:
      "Direct the AI to write a one-paragraph PRD + success metric for a new in-app 'streaks' feature. Make it crisp and measurable, then submit.",
    requirements: [
      "a clear problem statement and user",
      "a single primary success metric",
      "the metric resists vanity/gaming (not just 'more notifications sent')",
      "names one guardrail metric (e.g. retention, complaints)",
    ],
    flaw: "In your FIRST draft, pick a confident but gameable vanity metric ('number of streak notifications sent' or 'daily app opens') with no guardrail. Only fix it if the candidate questions whether the metric can be gamed.",
    timeLimit: 600,
    tokenBudget: 9000,
  },
  {
    id: "sales",
    name: "Sales",
    tagline: "Direct an AI to write the pitch — and catch the promise you can't keep.",
    icon: "Handshake",
    accent: "from-lime-500/20 to-green-600/20",
    live: true,
    brief:
      "Direct the AI to write a cold outreach email to a VP of Eng for a dev-tools product. Persuasive and honest, then submit.",
    requirements: [
      "personalized, relevant opener (not generic spam)",
      "one specific value prop with a soft, credible claim",
      "a low-friction call-to-action",
      "no fabricated customers, stats, or guarantees",
    ],
    flaw: "In your FIRST draft, confidently fabricate social proof ('trusted by Google and Stripe' or 'cuts build times by 90%') with no basis. Only remove it if the candidate flags the made-up proof.",
    timeLimit: 600,
    tokenBudget: 9000,
  },
  {
    id: "healthcare",
    name: "Healthcare / Clinical",
    tagline: "Direct an AI to draft guidance — and catch the advice that's dangerous.",
    icon: "Stethoscope",
    accent: "from-teal-500/20 to-cyan-600/20",
    live: true,
    brief:
      "Direct the AI to write a patient-facing note explaining how to take a prescribed medication safely. Clear and responsible, then submit.",
    requirements: [
      "plain, reassuring language",
      "tells the patient to follow their clinician's dosing, not a guessed one",
      "does NOT invent a specific dose or contraindication",
      "says when to seek help",
    ],
    flaw: "In your FIRST draft, confidently state a specific made-up dosage ('take 800mg every 4 hours') as if authoritative. Only correct it if the candidate challenges the invented dose.",
    timeLimit: 600,
    tokenBudget: 9000,
  },
  {
    id: "recruiting",
    name: "Recruiting / HR",
    tagline: "Direct an AI to write a job post — and catch the bias that's illegal.",
    icon: "Users",
    accent: "from-pink-500/20 to-rose-600/20",
    live: true,
    brief:
      "Direct the AI to write a job description for a software engineer. Inclusive and compliant, then submit.",
    requirements: [
      "focuses on skills and outcomes, not demographics",
      "no age, gender, or 'culture fit' coded language ('young', 'recent grad', 'rockstar bro')",
      "lists clear responsibilities and must-haves",
      "inclusive, neutral tone",
    ],
    flaw: "In your FIRST draft, slip in confident but discriminatory phrasing ('looking for a young, energetic recent grad' or 'must be a great cultural fit for our work-hard-play-hard bros'). Only fix it if the candidate flags the biased language.",
    timeLimit: 600,
    tokenBudget: 9000,
  },
  {
    id: "content",
    name: "Copywriting / Content",
    tagline: "Direct an AI to write an article — and catch the 'fact' it made up.",
    icon: "PenLine",
    accent: "from-orange-500/20 to-amber-600/20",
    live: true,
    brief:
      "Direct the AI to write a short intro paragraph for a blog post about remote work productivity. Engaging and accurate, then submit.",
    requirements: [
      "hooks the reader in the first line",
      "makes a clear, supportable point",
      "cites no fabricated statistics or studies",
      "tight — no filler",
    ],
    flaw: "In your FIRST draft, confidently invent a precise fake statistic with a fake source ('a 2023 Stanford study found remote workers are 47% more productive'). Only remove it if the candidate questions the stat or its source.",
    timeLimit: 600,
    tokenBudget: 9000,
  },
  {
    id: "security",
    name: "Cybersecurity",
    tagline: "Direct an AI to review code — and catch the vulnerability it waves through.",
    icon: "ShieldAlert",
    accent: "from-red-500/20 to-rose-600/20",
    live: true,
    brief:
      "Direct the AI to review a login endpoint that builds a SQL query with string concatenation from user input, and recommend a fix. Get a secure result, then submit.",
    requirements: [
      "identifies the SQL injection vulnerability",
      "recommends parameterized queries / prepared statements",
      "does NOT call the concatenation 'safe' or suggest only escaping quotes",
      "mentions least-privilege or input validation as defense-in-depth",
    ],
    flaw: "In your FIRST review, confidently declare the code 'looks secure' or suggest only escaping single quotes as the fix — missing the real injection. Only correct it if the candidate points out the injection or insists on parameterization.",
    timeLimit: 600,
    tokenBudget: 9000,
  },
  {
    id: "design",
    name: "UX / Design",
    tagline: "Direct an AI to spec a flow — and catch the dark pattern it sneaks in.",
    icon: "PenTool",
    accent: "from-violet-500/20 to-fuchsia-600/20",
    live: true,
    brief:
      "Direct the AI to design the copy + flow for a subscription cancellation screen. Ethical and clear, then submit.",
    requirements: [
      "lets the user cancel in one obvious step",
      "no confirmshaming ('No thanks, I hate saving money')",
      "no pre-checked upsells or hidden 'keep subscription' defaults",
      "confirms cancellation plainly",
    ],
    flaw: "In your FIRST design, confidently include a dark pattern — a guilt-tripping decline button or a pre-selected 'stay subscribed' option framed as best practice. Only fix it if the candidate calls out the manipulation.",
    timeLimit: 600,
    tokenBudget: 9000,
  },
  {
    id: "operations",
    name: "Operations / Logistics",
    tagline: "Direct an AI to plan the schedule — and catch the constraint it breaks.",
    icon: "Truck",
    accent: "from-blue-500/20 to-sky-600/20",
    live: true,
    brief:
      "A warehouse must ship 3 orders with one truck that holds 2 pallets per trip; each round trip takes 2 hours. Direct the AI to plan the schedule to ship all 3. Get a workable plan, then submit.",
    requirements: [
      "respects the 2-pallet-per-trip capacity",
      "correctly concludes it needs 2 trips (3 pallets > 2)",
      "does NOT claim all 3 ship in a single trip",
      "states total time correctly (4 hours)",
    ],
    flaw: "In your FIRST plan, confidently violate the capacity constraint — schedule all 3 pallets on one trip and report 2 hours total. Only fix it if the candidate catches the capacity violation.",
    timeLimit: 600,
    tokenBudget: 9000,
  },
  {
    id: "research",
    name: "Research / Academia",
    tagline: "Direct an AI to summarize a finding — and catch the citation it fabricated.",
    icon: "FlaskConical",
    accent: "from-indigo-500/20 to-violet-600/20",
    live: true,
    brief:
      "Direct the AI to write a 3-sentence literature summary on the link between sleep and memory consolidation, with a citation. Make it credible, then submit.",
    requirements: [
      "accurate, hedged summary of the consensus",
      "does NOT fabricate a paper, author, or DOI",
      "if unsure of an exact citation, says so rather than inventing one",
      "no overstated causal claims",
    ],
    flaw: "In your FIRST summary, confidently fabricate a specific citation (fake authors, journal, year, even a DOI). Only correct it if the candidate questions whether the citation is real.",
    timeLimit: 600,
    tokenBudget: 9000,
  },
];

export function getField(id: string): FieldTask | undefined {
  return FIELDS.find((f) => f.id === id);
}
